
[env]
TERM = "xterm-256color" # Fix colorscheme

# Cursor
[cursor]
style = { shape = "Beam", blinking = "Off" }

# Font
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 16.0

[general]
import = [
    "~/.config/alacritty/catppuccin-frappe.toml"
]
